#! /usr/bin/env bash
exec /home/darkspartan345/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0x2e984410 .scope module, "tb_multiplier_8bit" "tb_multiplier_8bit" 2 3;
 .timescale -9 -12;
v0x2e9a8e10_0 .var "A", 1 0;
v0x2e9a8ed0_0 .var "B", 1 0;
v0x2e9a8f70_0 .net "P", 3 0, L_0x2e9aa1a0;  1 drivers
S_0x2e9845a0 .scope module, "uut" "multiplier" 2 12, 3 3 0, S_0x2e984410;
 .timescale -9 -12;
    .port_info 0 /INPUT 2 "A";
    .port_info 1 /INPUT 2 "B";
    .port_info 2 /OUTPUT 4 "P";
L_0x2e9a91a0 .functor NOT 1, L_0x2e9a90b0, C4<0>, C4<0>, C4<0>;
L_0x2e9a9260 .functor AND 1, L_0x2e9a9010, L_0x2e9a91a0, C4<1>, C4<1>;
L_0x2e9a9410 .functor NOT 1, L_0x2e9a9370, C4<0>, C4<0>, C4<0>;
L_0x2e9a95a0 .functor AND 1, L_0x2e9a9410, L_0x2e9a94d0, C4<1>, C4<1>;
v0x2e949140_0 .net "A", 1 0, v0x2e9a8e10_0;  1 drivers
v0x2e9a78a0_0 .net "B", 1 0, v0x2e9a8ed0_0;  1 drivers
v0x2e9a7980_0 .net "P", 3 0, L_0x2e9aa1a0;  alias, 1 drivers
v0x2e9a7a40_0 .net *"_ivl_1", 0 0, L_0x2e9a9010;  1 drivers
v0x2e9a7b20_0 .net *"_ivl_10", 0 0, L_0x2e9a9410;  1 drivers
v0x2e9a7c50_0 .net *"_ivl_13", 0 0, L_0x2e9a94d0;  1 drivers
L_0x7f07d9165018 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x2e9a7d30_0 .net *"_ivl_19", 0 0, L_0x7f07d9165018;  1 drivers
L_0x7f07d9165060 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x2e9a7e10_0 .net *"_ivl_23", 0 0, L_0x7f07d9165060;  1 drivers
v0x2e9a7ef0_0 .net *"_ivl_24", 3 0, L_0x2e9a99a0;  1 drivers
L_0x7f07d91650a8 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x2e9a7fd0_0 .net *"_ivl_27", 1 0, L_0x7f07d91650a8;  1 drivers
v0x2e9a80b0_0 .net *"_ivl_28", 3 0, L_0x2e9a9c20;  1 drivers
v0x2e9a8190_0 .net *"_ivl_3", 0 0, L_0x2e9a90b0;  1 drivers
v0x2e9a8270_0 .net *"_ivl_30", 0 0, L_0x2e9a9ae0;  1 drivers
L_0x7f07d91650f0 .functor BUFT 1, C4<000>, C4<0>, C4<0>, C4<0>;
v0x2e9a8350_0 .net *"_ivl_32", 2 0, L_0x7f07d91650f0;  1 drivers
v0x2e9a8430_0 .net *"_ivl_34", 3 0, L_0x2e9a9d60;  1 drivers
L_0x7f07d9165138 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x2e9a8510_0 .net *"_ivl_37", 1 0, L_0x7f07d9165138;  1 drivers
v0x2e9a85f0_0 .net *"_ivl_38", 3 0, L_0x2e9a9ff0;  1 drivers
v0x2e9a86d0_0 .net *"_ivl_4", 0 0, L_0x2e9a91a0;  1 drivers
v0x2e9a87b0_0 .net *"_ivl_40", 2 0, L_0x2e9a9f00;  1 drivers
L_0x7f07d9165180 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x2e9a8890_0 .net *"_ivl_42", 0 0, L_0x7f07d9165180;  1 drivers
v0x2e9a8970_0 .net *"_ivl_9", 0 0, L_0x2e9a9370;  1 drivers
v0x2e9a8a50_0 .net "columna2", 1 0, L_0x2e9a9820;  1 drivers
v0x2e9a8b30_0 .net "columna4", 1 0, L_0x2e9a96e0;  1 drivers
v0x2e9a8c10_0 .net "pp0", 0 0, L_0x2e9a9260;  1 drivers
v0x2e9a8cd0_0 .net "pp1", 0 0, L_0x2e9a95a0;  1 drivers
L_0x2e9a9010 .part v0x2e9a8e10_0, 1, 1;
L_0x2e9a90b0 .part v0x2e9a8ed0_0, 1, 1;
L_0x2e9a9370 .part v0x2e9a8e10_0, 1, 1;
L_0x2e9a94d0 .part v0x2e9a8ed0_0, 1, 1;
L_0x2e9a96e0 .concat [ 1 1 0 0], L_0x2e9a95a0, L_0x7f07d9165018;
L_0x2e9a9820 .concat [ 1 1 0 0], L_0x2e9a9260, L_0x7f07d9165060;
L_0x2e9a99a0 .concat [ 2 2 0 0], L_0x2e9a96e0, L_0x7f07d91650a8;
L_0x2e9a9ae0 .part L_0x2e9a99a0, 0, 1;
L_0x2e9a9c20 .concat [ 3 1 0 0], L_0x7f07d91650f0, L_0x2e9a9ae0;
L_0x2e9a9d60 .concat [ 2 2 0 0], L_0x2e9a9820, L_0x7f07d9165138;
L_0x2e9a9f00 .part L_0x2e9a9d60, 0, 3;
L_0x2e9a9ff0 .concat [ 1 3 0 0], L_0x7f07d9165180, L_0x2e9a9f00;
L_0x2e9aa1a0 .arith/sum 4, L_0x2e9a9c20, L_0x2e9a9ff0;
    .scope S_0x2e984410;
T_0 ;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 25 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 32 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 39 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 46 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 53 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 60 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 67 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 74 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 81 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 88 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 95 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 102 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 109 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 116 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 123 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 130 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 137 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 144 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 151 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8e10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x2e9a8ed0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 158 "$display", "%d", v0x2e9a8f70_0 {0 0 0};
    %vpi_call 2 162 "$finish" {0 0 0};
    %end;
    .thread T_0;
    .scope S_0x2e984410;
T_1 ;
    %vpi_call 2 167 "$dumpfile", "multiplier_8bit_tb.vcd" {0 0 0};
    %vpi_call 2 168 "$dumpvars", 32'sb00000000000000000000000000000000, S_0x2e984410 {0 0 0};
    %end;
    .thread T_1;
# The file index is used to find the file name in the following table.
:file_names 4;
    "N/A";
    "<interactive>";
    "Verilog/multiplier_8bit_tb_env_5_2.v";
    "Verilog/multiplier_env_5_2.v";
# EOF
