#! /usr/bin/env bash
exec /home/darkspartan345/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0x3e3c7970 .scope module, "tb_multiplier_8bit" "tb_multiplier_8bit" 2 3;
 .timescale -9 -12;
v0x3e3ee7d0_0 .var "A", 1 0;
v0x3e3ee890_0 .var "B", 1 0;
v0x3e3ee930_0 .net "P", 3 0, L_0x3e3f0200;  1 drivers
S_0x3e3c7b00 .scope module, "uut" "multiplier" 2 12, 3 3 0, S_0x3e3c7970;
 .timescale -9 -12;
    .port_info 0 /INPUT 2 "A";
    .port_info 1 /INPUT 2 "B";
    .port_info 2 /OUTPUT 4 "P";
L_0x71822eee3060 .functor BUFT 1, C4<01>, C4<0>, C4<0>, C4<0>;
L_0x3e3eebb0 .functor AND 2, L_0x3e3eea70, L_0x71822eee3060, C4<11>, C4<11>;
L_0x71822eee30f0 .functor BUFT 1, C4<01>, C4<0>, C4<0>, C4<0>;
L_0x3e3eefc0 .functor AND 2, L_0x3e3eee80, L_0x71822eee30f0, C4<11>, C4<11>;
L_0x3e3ef2d0 .functor NOT 1, L_0x3e3ef230, C4<0>, C4<0>, C4<0>;
L_0x3e3ef480 .functor AND 1, L_0x3e3ef2d0, L_0x3e3ef340, C4<1>, C4<1>;
v0x3e38c140_0 .net "A", 1 0, v0x3e3ee7d0_0;  1 drivers
v0x3e3ecb80_0 .net "B", 1 0, v0x3e3ee890_0;  1 drivers
v0x3e3ecc60_0 .net "P", 3 0, L_0x3e3f0200;  alias, 1 drivers
v0x3e3ecd20_0 .net *"_ivl_1", 0 0, L_0x3e3ee9d0;  1 drivers
v0x3e3ece00_0 .net *"_ivl_13", 0 0, L_0x3e3eedb0;  1 drivers
v0x3e3ecf30_0 .net *"_ivl_14", 1 0, L_0x3e3eee80;  1 drivers
L_0x71822eee30a8 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x3e3ed010_0 .net *"_ivl_17", 0 0, L_0x71822eee30a8;  1 drivers
v0x3e3ed0f0_0 .net/2u *"_ivl_18", 1 0, L_0x71822eee30f0;  1 drivers
v0x3e3ed1d0_0 .net *"_ivl_2", 1 0, L_0x3e3eea70;  1 drivers
v0x3e3ed2b0_0 .net *"_ivl_20", 1 0, L_0x3e3eefc0;  1 drivers
v0x3e3ed390_0 .net *"_ivl_25", 0 0, L_0x3e3ef230;  1 drivers
v0x3e3ed470_0 .net *"_ivl_26", 0 0, L_0x3e3ef2d0;  1 drivers
v0x3e3ed550_0 .net *"_ivl_29", 0 0, L_0x3e3ef340;  1 drivers
L_0x71822eee3138 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x3e3ed630_0 .net *"_ivl_35", 0 0, L_0x71822eee3138;  1 drivers
v0x3e3ed710_0 .net *"_ivl_36", 1 0, L_0x3e3ef750;  1 drivers
L_0x71822eee3180 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x3e3ed7f0_0 .net *"_ivl_39", 0 0, L_0x71822eee3180;  1 drivers
v0x3e3ed8d0_0 .net *"_ivl_40", 1 0, L_0x3e3ef8a0;  1 drivers
L_0x71822eee31c8 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x3e3ed9b0_0 .net *"_ivl_43", 0 0, L_0x71822eee31c8;  1 drivers
v0x3e3eda90_0 .net *"_ivl_46", 3 0, L_0x3e3efc00;  1 drivers
L_0x71822eee3210 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x3e3edb70_0 .net *"_ivl_49", 1 0, L_0x71822eee3210;  1 drivers
L_0x71822eee3018 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x3e3edc50_0 .net *"_ivl_5", 0 0, L_0x71822eee3018;  1 drivers
v0x3e3edd30_0 .net *"_ivl_50", 3 0, L_0x3e3eff40;  1 drivers
v0x3e3ede10_0 .net *"_ivl_52", 0 0, L_0x3e3efd40;  1 drivers
L_0x71822eee3258 .functor BUFT 1, C4<000>, C4<0>, C4<0>, C4<0>;
v0x3e3edef0_0 .net *"_ivl_54", 2 0, L_0x71822eee3258;  1 drivers
v0x3e3edfd0_0 .net *"_ivl_56", 3 0, L_0x3e3f0030;  1 drivers
L_0x71822eee32a0 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x3e3ee0b0_0 .net *"_ivl_59", 1 0, L_0x71822eee32a0;  1 drivers
v0x3e3ee190_0 .net/2u *"_ivl_6", 1 0, L_0x71822eee3060;  1 drivers
v0x3e3ee270_0 .net *"_ivl_8", 1 0, L_0x3e3eebb0;  1 drivers
v0x3e3ee350_0 .net "columna1", 1 0, L_0x3e3ef9e0;  1 drivers
v0x3e3ee430_0 .net "columna4", 1 0, L_0x3e3ef5c0;  1 drivers
v0x3e3ee510_0 .net "pp0", 0 0, L_0x3e3eecc0;  1 drivers
v0x3e3ee5d0_0 .net "pp1", 0 0, L_0x3e3ef100;  1 drivers
v0x3e3ee690_0 .net "pp2", 0 0, L_0x3e3ef480;  1 drivers
L_0x3e3ee9d0 .part v0x3e3ee7d0_0, 1, 1;
L_0x3e3eea70 .concat [ 1 1 0 0], L_0x3e3ee9d0, L_0x71822eee3018;
L_0x3e3eecc0 .part L_0x3e3eebb0, 0, 1;
L_0x3e3eedb0 .part v0x3e3ee7d0_0, 0, 1;
L_0x3e3eee80 .concat [ 1 1 0 0], L_0x3e3eedb0, L_0x71822eee30a8;
L_0x3e3ef100 .part L_0x3e3eefc0, 0, 1;
L_0x3e3ef230 .part v0x3e3ee7d0_0, 1, 1;
L_0x3e3ef340 .part v0x3e3ee890_0, 1, 1;
L_0x3e3ef5c0 .concat [ 1 1 0 0], L_0x3e3ef100, L_0x71822eee3138;
L_0x3e3ef750 .concat [ 1 1 0 0], L_0x3e3eecc0, L_0x71822eee3180;
L_0x3e3ef8a0 .concat [ 1 1 0 0], L_0x3e3ef480, L_0x71822eee31c8;
L_0x3e3ef9e0 .arith/sum 2, L_0x3e3ef750, L_0x3e3ef8a0;
L_0x3e3efc00 .concat [ 2 2 0 0], L_0x3e3ef5c0, L_0x71822eee3210;
L_0x3e3efd40 .part L_0x3e3efc00, 0, 1;
L_0x3e3eff40 .concat [ 3 1 0 0], L_0x71822eee3258, L_0x3e3efd40;
L_0x3e3f0030 .concat [ 2 2 0 0], L_0x3e3ef9e0, L_0x71822eee32a0;
L_0x3e3f0200 .arith/sum 4, L_0x3e3eff40, L_0x3e3f0030;
    .scope S_0x3e3c7970;
T_0 ;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 25 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 32 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 39 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 46 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 53 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 60 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 67 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 74 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 81 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 88 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 95 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 102 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 109 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 116 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 123 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 130 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 137 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 144 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 151 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x3e3ee7d0_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x3e3ee890_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 158 "$display", "%d", v0x3e3ee930_0 {0 0 0};
    %vpi_call 2 162 "$finish" {0 0 0};
    %end;
    .thread T_0;
    .scope S_0x3e3c7970;
T_1 ;
    %vpi_call 2 167 "$dumpfile", "multiplier_8bit_tb.vcd" {0 0 0};
    %vpi_call 2 168 "$dumpvars", 32'sb00000000000000000000000000000000, S_0x3e3c7970 {0 0 0};
    %end;
    .thread T_1;
# The file index is used to find the file name in the following table.
:file_names 4;
    "N/A";
    "<interactive>";
    "Verilog/multiplier_8bit_tb_env_11_2.v";
    "Verilog/multiplier_env_11_2.v";
# EOF
