#! /usr/bin/env bash
exec /home/darkspartan345/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0x34bc0830 .scope module, "tb_multiplier_8bit" "tb_multiplier_8bit" 2 3;
 .timescale -9 -12;
v0x34beaa70_0 .var "A", 1 0;
v0x34beab30_0 .var "B", 1 0;
v0x34beabd0_0 .net "P", 3 0, L_0x34becd90;  1 drivers
S_0x34bc09c0 .scope module, "uut" "multiplier" 2 12, 3 3 0, S_0x34bc0830;
 .timescale -9 -12;
    .port_info 0 /INPUT 2 "A";
    .port_info 1 /INPUT 2 "B";
    .port_info 2 /OUTPUT 4 "P";
L_0x34bead10 .functor NOT 1, L_0x34beac70, C4<0>, C4<0>, C4<0>;
L_0x34beaec0 .functor NOT 1, L_0x34beadd0, C4<0>, C4<0>, C4<0>;
L_0x34beaf80 .functor AND 1, L_0x34bead10, L_0x34beaec0, C4<1>, C4<1>;
L_0x34beb200 .functor NOT 1, L_0x34beb130, C4<0>, C4<0>, C4<0>;
L_0x34beb2f0 .functor AND 1, L_0x34beb090, L_0x34beb200, C4<1>, C4<1>;
L_0x34beb4a0 .functor NOT 1, L_0x34beb400, C4<0>, C4<0>, C4<0>;
L_0x34beb6c0 .functor AND 1, L_0x34beb4a0, L_0x34beb550, C4<1>, C4<1>;
v0x34bc0b50_0 .net "A", 1 0, v0x34beaa70_0;  1 drivers
v0x34be8560_0 .net "B", 1 0, v0x34beab30_0;  1 drivers
v0x34be8640_0 .net "P", 3 0, L_0x34becd90;  alias, 1 drivers
v0x34be8700_0 .net *"_ivl_1", 0 0, L_0x34beac70;  1 drivers
v0x34be87e0_0 .net *"_ivl_11", 0 0, L_0x34beb090;  1 drivers
v0x34be8910_0 .net *"_ivl_13", 0 0, L_0x34beb130;  1 drivers
v0x34be89f0_0 .net *"_ivl_14", 0 0, L_0x34beb200;  1 drivers
v0x34be8ad0_0 .net *"_ivl_19", 0 0, L_0x34beb400;  1 drivers
v0x34be8bb0_0 .net *"_ivl_2", 0 0, L_0x34bead10;  1 drivers
v0x34be8c90_0 .net *"_ivl_20", 0 0, L_0x34beb4a0;  1 drivers
v0x34be8d70_0 .net *"_ivl_23", 0 0, L_0x34beb550;  1 drivers
L_0x753957ca4018 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x34be8e50_0 .net *"_ivl_29", 0 0, L_0x753957ca4018;  1 drivers
L_0x753957ca4060 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x34be8f30_0 .net *"_ivl_33", 0 0, L_0x753957ca4060;  1 drivers
L_0x753957ca40a8 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x34be9010_0 .net *"_ivl_37", 0 0, L_0x753957ca40a8;  1 drivers
L_0x753957ca40f0 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x34be90f0_0 .net *"_ivl_41", 0 0, L_0x753957ca40f0;  1 drivers
v0x34be91d0_0 .net *"_ivl_42", 3 0, L_0x34bebc90;  1 drivers
L_0x753957ca4138 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x34be92b0_0 .net *"_ivl_45", 1 0, L_0x753957ca4138;  1 drivers
v0x34be9390_0 .net *"_ivl_46", 3 0, L_0x34bebf80;  1 drivers
v0x34be9470_0 .net *"_ivl_48", 0 0, L_0x34bebe20;  1 drivers
v0x34be9550_0 .net *"_ivl_5", 0 0, L_0x34beadd0;  1 drivers
L_0x753957ca4180 .functor BUFT 1, C4<000>, C4<0>, C4<0>, C4<0>;
v0x34be9630_0 .net *"_ivl_50", 2 0, L_0x753957ca4180;  1 drivers
v0x34be9710_0 .net *"_ivl_52", 3 0, L_0x34bec0c0;  1 drivers
L_0x753957ca41c8 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x34be97f0_0 .net *"_ivl_55", 1 0, L_0x753957ca41c8;  1 drivers
v0x34be98d0_0 .net *"_ivl_56", 3 0, L_0x34bec370;  1 drivers
v0x34be99b0_0 .net *"_ivl_58", 1 0, L_0x34bec280;  1 drivers
v0x34be9a90_0 .net *"_ivl_6", 0 0, L_0x34beaec0;  1 drivers
L_0x753957ca4210 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x34be9b70_0 .net *"_ivl_60", 1 0, L_0x753957ca4210;  1 drivers
v0x34be9c50_0 .net *"_ivl_62", 3 0, L_0x34bec540;  1 drivers
v0x34be9d30_0 .net *"_ivl_64", 3 0, L_0x34bec680;  1 drivers
L_0x753957ca4258 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x34be9e10_0 .net *"_ivl_67", 1 0, L_0x753957ca4258;  1 drivers
v0x34be9ef0_0 .net *"_ivl_68", 3 0, L_0x34bec900;  1 drivers
v0x34be9fd0_0 .net *"_ivl_70", 2 0, L_0x34bec860;  1 drivers
L_0x753957ca42a0 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x34bea0b0_0 .net *"_ivl_72", 0 0, L_0x753957ca42a0;  1 drivers
v0x34bea190_0 .net *"_ivl_74", 3 0, L_0x34bec770;  1 drivers
v0x34bea270_0 .net *"_ivl_76", 3 0, L_0x34becb90;  1 drivers
L_0x753957ca42e8 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x34bea350_0 .net *"_ivl_79", 1 0, L_0x753957ca42e8;  1 drivers
v0x34bea430_0 .net "columna1", 1 0, L_0x34bebb90;  1 drivers
v0x34bea510_0 .net "columna2", 1 0, L_0x34beba50;  1 drivers
v0x34bea5f0_0 .net "columna3", 1 0, L_0x34beb8c0;  1 drivers
v0x34bea6d0_0 .net "columna4", 1 0, L_0x34beb780;  1 drivers
v0x34bea7b0_0 .net "pp0", 0 0, L_0x34beaf80;  1 drivers
v0x34bea870_0 .net "pp1", 0 0, L_0x34beb2f0;  1 drivers
v0x34bea930_0 .net "pp2", 0 0, L_0x34beb6c0;  1 drivers
L_0x34beac70 .part v0x34beaa70_0, 1, 1;
L_0x34beadd0 .part v0x34beab30_0, 0, 1;
L_0x34beb090 .part v0x34beaa70_0, 1, 1;
L_0x34beb130 .part v0x34beab30_0, 1, 1;
L_0x34beb400 .part v0x34beaa70_0, 1, 1;
L_0x34beb550 .part v0x34beab30_0, 0, 1;
L_0x34beb780 .concat [ 1 1 0 0], L_0x34beb2f0, L_0x753957ca4018;
L_0x34beb8c0 .concat [ 1 1 0 0], L_0x34beaf80, L_0x753957ca4060;
L_0x34beba50 .concat [ 1 1 0 0], L_0x34beb6c0, L_0x753957ca40a8;
L_0x34bebb90 .concat [ 1 1 0 0], L_0x34beb2f0, L_0x753957ca40f0;
L_0x34bebc90 .concat [ 2 2 0 0], L_0x34beb780, L_0x753957ca4138;
L_0x34bebe20 .part L_0x34bebc90, 0, 1;
L_0x34bebf80 .concat [ 3 1 0 0], L_0x753957ca4180, L_0x34bebe20;
L_0x34bec0c0 .concat [ 2 2 0 0], L_0x34beb8c0, L_0x753957ca41c8;
L_0x34bec280 .part L_0x34bec0c0, 0, 2;
L_0x34bec370 .concat [ 2 2 0 0], L_0x753957ca4210, L_0x34bec280;
L_0x34bec540 .arith/sum 4, L_0x34bebf80, L_0x34bec370;
L_0x34bec680 .concat [ 2 2 0 0], L_0x34beba50, L_0x753957ca4258;
L_0x34bec860 .part L_0x34bec680, 0, 3;
L_0x34bec900 .concat [ 1 3 0 0], L_0x753957ca42a0, L_0x34bec860;
L_0x34bec770 .arith/sum 4, L_0x34bec540, L_0x34bec900;
L_0x34becb90 .concat [ 2 2 0 0], L_0x34bebb90, L_0x753957ca42e8;
L_0x34becd90 .arith/sum 4, L_0x34bec770, L_0x34becb90;
    .scope S_0x34bc0830;
T_0 ;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 25 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 32 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 39 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 46 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 53 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 60 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 67 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 74 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 81 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 88 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 95 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 102 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 109 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 116 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 123 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 130 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 137 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 144 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 151 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x34beaa70_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x34beab30_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 158 "$display", "%d", v0x34beabd0_0 {0 0 0};
    %vpi_call 2 162 "$finish" {0 0 0};
    %end;
    .thread T_0;
    .scope S_0x34bc0830;
T_1 ;
    %vpi_call 2 167 "$dumpfile", "multiplier_8bit_tb.vcd" {0 0 0};
    %vpi_call 2 168 "$dumpvars", 32'sb00000000000000000000000000000000, S_0x34bc0830 {0 0 0};
    %end;
    .thread T_1;
# The file index is used to find the file name in the following table.
:file_names 4;
    "N/A";
    "<interactive>";
    "Verilog/multiplier_8bit_tb_env_4_2.v";
    "Verilog/multiplier_env_4_2.v";
# EOF
