#! /usr/bin/env bash
exec /home/darkspartan345/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/darkspartan345/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0x9a58410 .scope module, "tb_multiplier_8bit" "tb_multiplier_8bit" 2 3;
 .timescale -9 -12;
v0x9a7ce10_0 .var "A", 1 0;
v0x9a7ced0_0 .var "B", 1 0;
v0x9a7cf70_0 .net "P", 3 0, L_0x9a7e1a0;  1 drivers
S_0x9a585a0 .scope module, "uut" "multiplier" 2 12, 3 3 0, S_0x9a58410;
 .timescale -9 -12;
    .port_info 0 /INPUT 2 "A";
    .port_info 1 /INPUT 2 "B";
    .port_info 2 /OUTPUT 4 "P";
L_0x9a7d1a0 .functor AND 1, L_0x9a7d010, L_0x9a7d0b0, C4<1>, C4<1>;
L_0x9a7d350 .functor NOT 1, L_0x9a7d2b0, C4<0>, C4<0>, C4<0>;
L_0x9a7d4e0 .functor NOT 1, L_0x9a7d410, C4<0>, C4<0>, C4<0>;
L_0x9a7d5a0 .functor AND 1, L_0x9a7d350, L_0x9a7d4e0, C4<1>, C4<1>;
v0x9a1d140_0 .net "A", 1 0, v0x9a7ce10_0;  1 drivers
v0x9a7b8a0_0 .net "B", 1 0, v0x9a7ced0_0;  1 drivers
v0x9a7b980_0 .net "P", 3 0, L_0x9a7e1a0;  alias, 1 drivers
v0x9a7ba40_0 .net *"_ivl_1", 0 0, L_0x9a7d010;  1 drivers
v0x9a7bb20_0 .net *"_ivl_11", 0 0, L_0x9a7d410;  1 drivers
v0x9a7bc50_0 .net *"_ivl_12", 0 0, L_0x9a7d4e0;  1 drivers
L_0x7b56b605d018 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x9a7bd30_0 .net *"_ivl_19", 0 0, L_0x7b56b605d018;  1 drivers
L_0x7b56b605d060 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x9a7be10_0 .net *"_ivl_23", 0 0, L_0x7b56b605d060;  1 drivers
v0x9a7bef0_0 .net *"_ivl_24", 3 0, L_0x9a7d9a0;  1 drivers
L_0x7b56b605d0a8 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x9a7bfd0_0 .net *"_ivl_27", 1 0, L_0x7b56b605d0a8;  1 drivers
v0x9a7c0b0_0 .net *"_ivl_28", 3 0, L_0x9a7dc20;  1 drivers
v0x9a7c190_0 .net *"_ivl_3", 0 0, L_0x9a7d0b0;  1 drivers
v0x9a7c270_0 .net *"_ivl_30", 0 0, L_0x9a7dae0;  1 drivers
L_0x7b56b605d0f0 .functor BUFT 1, C4<000>, C4<0>, C4<0>, C4<0>;
v0x9a7c350_0 .net *"_ivl_32", 2 0, L_0x7b56b605d0f0;  1 drivers
v0x9a7c430_0 .net *"_ivl_34", 3 0, L_0x9a7dd60;  1 drivers
L_0x7b56b605d138 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x9a7c510_0 .net *"_ivl_37", 1 0, L_0x7b56b605d138;  1 drivers
v0x9a7c5f0_0 .net *"_ivl_38", 3 0, L_0x9a7dff0;  1 drivers
v0x9a7c6d0_0 .net *"_ivl_40", 1 0, L_0x9a7df00;  1 drivers
L_0x7b56b605d180 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x9a7c7b0_0 .net *"_ivl_42", 1 0, L_0x7b56b605d180;  1 drivers
v0x9a7c890_0 .net *"_ivl_7", 0 0, L_0x9a7d2b0;  1 drivers
v0x9a7c970_0 .net *"_ivl_8", 0 0, L_0x9a7d350;  1 drivers
v0x9a7ca50_0 .net "columna3", 1 0, L_0x9a7d820;  1 drivers
v0x9a7cb30_0 .net "columna4", 1 0, L_0x9a7d6e0;  1 drivers
v0x9a7cc10_0 .net "pp0", 0 0, L_0x9a7d1a0;  1 drivers
v0x9a7ccd0_0 .net "pp1", 0 0, L_0x9a7d5a0;  1 drivers
L_0x9a7d010 .part v0x9a7ce10_0, 0, 1;
L_0x9a7d0b0 .part v0x9a7ced0_0, 0, 1;
L_0x9a7d2b0 .part v0x9a7ce10_0, 0, 1;
L_0x9a7d410 .part v0x9a7ced0_0, 1, 1;
L_0x9a7d6e0 .concat [ 1 1 0 0], L_0x9a7d1a0, L_0x7b56b605d018;
L_0x9a7d820 .concat [ 1 1 0 0], L_0x9a7d5a0, L_0x7b56b605d060;
L_0x9a7d9a0 .concat [ 2 2 0 0], L_0x9a7d6e0, L_0x7b56b605d0a8;
L_0x9a7dae0 .part L_0x9a7d9a0, 0, 1;
L_0x9a7dc20 .concat [ 3 1 0 0], L_0x7b56b605d0f0, L_0x9a7dae0;
L_0x9a7dd60 .concat [ 2 2 0 0], L_0x9a7d820, L_0x7b56b605d138;
L_0x9a7df00 .part L_0x9a7dd60, 0, 2;
L_0x9a7dff0 .concat [ 2 2 0 0], L_0x7b56b605d180, L_0x9a7df00;
L_0x9a7e1a0 .arith/sum 4, L_0x9a7dc20, L_0x9a7dff0;
    .scope S_0x9a58410;
T_0 ;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 25 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 32 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 39 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 46 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 53 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 60 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 67 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 74 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 81 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 88 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 95 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 102 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 109 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 116 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 123 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 130 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 137 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 144 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 2, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 1, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 151 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ce10_0, 0, 2;
    %pushi/vec4 3, 0, 2;
    %store/vec4 v0x9a7ced0_0, 0, 2;
    %delay 10000, 0;
    %vpi_call 2 158 "$display", "%d", v0x9a7cf70_0 {0 0 0};
    %vpi_call 2 162 "$finish" {0 0 0};
    %end;
    .thread T_0;
    .scope S_0x9a58410;
T_1 ;
    %vpi_call 2 167 "$dumpfile", "multiplier_8bit_tb.vcd" {0 0 0};
    %vpi_call 2 168 "$dumpvars", 32'sb00000000000000000000000000000000, S_0x9a58410 {0 0 0};
    %end;
    .thread T_1;
# The file index is used to find the file name in the following table.
:file_names 4;
    "N/A";
    "<interactive>";
    "Verilog/multiplier_8bit_tb_env_11_2.v";
    "Verilog/multiplier_env_11_2.v";
# EOF
